# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_logSimulationPoseDataDialog.ui'
#
# Created: Fri Dec 14 07:21:01 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_logSimulationPoseDataDialog(object):
    def setupUi(self, logSimulationPoseDataDialog):
        logSimulationPoseDataDialog.setObjectName(_fromUtf8("logSimulationPoseDataDialog"))
        logSimulationPoseDataDialog.resize(563, 290)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(logSimulationPoseDataDialog.sizePolicy().hasHeightForWidth())
        logSimulationPoseDataDialog.setSizePolicy(sizePolicy)
        self.layoutWidget = QtGui.QWidget(logSimulationPoseDataDialog)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 10, 521, 68))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lineEdit_map = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_map.setObjectName(_fromUtf8("lineEdit_map"))
        self.horizontalLayout.addWidget(self.lineEdit_map)
        self.pushButton_browse_map = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse_map.sizePolicy().hasHeightForWidth())
        self.pushButton_browse_map.setSizePolicy(sizePolicy)
        self.pushButton_browse_map.setObjectName(_fromUtf8("pushButton_browse_map"))
        self.horizontalLayout.addWidget(self.pushButton_browse_map)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lineEdit_log = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_log.setObjectName(_fromUtf8("lineEdit_log"))
        self.horizontalLayout_2.addWidget(self.lineEdit_log)
        self.pushButton_browse_log = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_browse_log.sizePolicy().hasHeightForWidth())
        self.pushButton_browse_log.setSizePolicy(sizePolicy)
        self.pushButton_browse_log.setObjectName(_fromUtf8("pushButton_browse_log"))
        self.horizontalLayout_2.addWidget(self.pushButton_browse_log)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.pushButton_start_logging = QtGui.QPushButton(logSimulationPoseDataDialog)
        self.pushButton_start_logging.setGeometry(QtCore.QRect(20, 200, 98, 27))
        self.pushButton_start_logging.setObjectName(_fromUtf8("pushButton_start_logging"))
        self.pushButton_generate_graph = QtGui.QPushButton(logSimulationPoseDataDialog)
        self.pushButton_generate_graph.setGeometry(QtCore.QRect(420, 200, 121, 27))
        self.pushButton_generate_graph.setObjectName(_fromUtf8("pushButton_generate_graph"))
        self.textEdit = QtGui.QTextEdit(logSimulationPoseDataDialog)
        self.textEdit.setGeometry(QtCore.QRect(20, 90, 521, 71))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.pushButton_ok = QtGui.QPushButton(logSimulationPoseDataDialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(440, 250, 101, 27))
        self.pushButton_ok.setObjectName(_fromUtf8("pushButton_ok"))
        self.pushButton_cancel = QtGui.QPushButton(logSimulationPoseDataDialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(330, 250, 98, 27))
        self.pushButton_cancel.setObjectName(_fromUtf8("pushButton_cancel"))
        self.pushButton_stop_logging = QtGui.QPushButton(logSimulationPoseDataDialog)
        self.pushButton_stop_logging.setGeometry(QtCore.QRect(140, 200, 98, 27))
        self.pushButton_stop_logging.setObjectName(_fromUtf8("pushButton_stop_logging"))
        self.label_3 = QtGui.QLabel(logSimulationPoseDataDialog)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 66, 17))
        self.label_3.setObjectName(_fromUtf8("label_3"))

        self.retranslateUi(logSimulationPoseDataDialog)
        QtCore.QMetaObject.connectSlotsByName(logSimulationPoseDataDialog)

    def retranslateUi(self, logSimulationPoseDataDialog):
        logSimulationPoseDataDialog.setWindowTitle(QtGui.QApplication.translate("logSimulationPoseDataDialog", "Log Simulation Pose Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("logSimulationPoseDataDialog", "Map File:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("logSimulationPoseDataDialog", "Log File:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_browse_map.setText(QtGui.QApplication.translate("logSimulationPoseDataDialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_browse_log.setText(QtGui.QApplication.translate("logSimulationPoseDataDialog", "Browse...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_start_logging.setText(QtGui.QApplication.translate("logSimulationPoseDataDialog", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_generate_graph.setText(QtGui.QApplication.translate("logSimulationPoseDataDialog", "Generate Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_ok.setText(QtGui.QApplication.translate("logSimulationPoseDataDialog", "Ok", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_cancel.setText(QtGui.QApplication.translate("logSimulationPoseDataDialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_stop_logging.setText(QtGui.QApplication.translate("logSimulationPoseDataDialog", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("logSimulationPoseDataDialog", "<b>Logging</b>", None, QtGui.QApplication.UnicodeUTF8))

